---
parameter_defaults:
  availability_zone: south-2
  volume_availability_zone: south-2
  network_availability_zone: south-2
  flavor_node: 4C-16GB-40GB
  flavor_manager: 4C-4GB-20GB
  image: OSISM base
  public: external
  volume_size_storage: 10
  ceph_version: nautilus
  openstack_version: train
