---
# Mapping of the labels of the used nodes to the cloud
# environment to be used.
cloud_envs:
  testbed-orchestrator: ci

# Mapping of the terraform environments to the image
# username to be used.
image_usernames:
  ci-ubuntu-24.04: ubuntu
  ci-debian-12: debian
  ci-centos-stream-9: cloud-user
