---
- name: Cleanup play
  hosts: all

  vars:
    repo_base: "github.com/osism"
    basepath: "{{ ansible_user_dir }}/src/{{ repo_base }}/testbed"
    cloud_env: managerless

  tasks:
    - name: Clean the cloud environment
      ansible.builtin.shell:
        cmd: |
          OS_CLOUD={{ cloud_env }} ~/venv/bin/python3 cleanup.py
        chdir: "{{ basepath }}/terraform/scripts"
      failed_when: false
      changed_when: true
