---
- name: Apply role osism.docker
  hosts: testbed-manager.osism.local
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_configure_repository: no
    docker_configure_storage_driver: yes
    docker_storage_driver: overlay2
    docker_user: dragon
    docker_version: "5:19.03.5"

  roles:
    - ansible-docker
