---
- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

    # ansible-common
    cleanup_services_common:
      - NetworkManager
      - iscsid
      - lxcfs
      - nscd
      - ntp
    cleanup_packages_common:
      - apport
      - apport-symptoms
      - dosfstools
      - libvirt-bin
      - lxc
      - lxd
      - ntfs-3g
      - open-iscsi
      - popularity-contest
      - python3-apport
      - snapd
      - telnet
      - ubuntu-server
      - xauth
    rng_enable_common: yes
    smartd_enable_common: no
    upgrade_packages_common: no

    # ansible-operator
    operator_user: dragon
    operator_group: dragon
    operator_authorized_keys:
      - "{{lookup('file', '/home/ubuntu/.ssh/id_rsa.pub')}}"

    # ansible-repository
    repository_cache_valid_time: 0
    repository_key_ids: {}
    repositories:
      - name: "{{ ansible_distribution_release }}-docker"
        repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      - name: "{{ ansible_distribution_release }}-netdata"
        repository: "deb [arch=amd64] https://packagecloud.io/netdata/netdata-edge/ubuntu/ {{ ansible_distribution_release }} main"
      - name: "{{ ansible_distribution_release }}"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted universe multiverse"
      - name: "{{ ansible_distribution_release }}-backports"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"
      - name: "{{ ansible_distribution_release }}-security"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security main restricted universe multiverse"
      - name: "{{ ansible_distribution_release }}-updates"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted universe multiverse"

  roles:
    - ansible-resolvconf
    - ansible-chrony
    - ansible-repository
    - ansible-common
    - ansible-operator
