---
docker_kata_install: yes

# NOTE: The testbed runs zun-compute on the node itself. Therefore the access
#       via TCP to Docker is necessary. This is not recommended for production.

docker_hosts:
  - "unix:///var/run/docker.sock"
  - "tcp://{{ internal_address }}:2375"

# NOTE: The cluster store is required because the nodes are used in Zun.

docker_opts:
  "cluster-store": "etcd://{{ internal_address }}:2379"
