---
name: Check python syntax

"on":
  push:
    paths:
      - '**.py'
      - '.github/workflows/check-python-syntax.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/check-python-syntax.yml'

jobs:
  check-python-syntax:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip3 install flake8
      - run: flake8
